### ISSUE TITLE
Tensorboard build-error

### ISSUE THREAD

**Issue by jorissijs** [rl-tools/rl-tools#8]
Heyhey,

first would like to mention that I really appreciate rl_tools. 

While trying out I encountered an error when building the examples that include the tensorboard option.  I receive a fatal error that 
"rl_tools/external/tensorboard/include/tensorboard_logger/tensorboard_logger.h:13:10: fatal error: event.pb.h: No such file or directory"

I do see the event.pb.h in rl_tools/build/external/tensorboard/proto  but not in rl_tools/external/tensorboard/proto.

Am I missing something.

Regards Joris

**Comment by jonas-eschmann** [comment]
Hi @jorissijs! 
Sorry that you're encountering this issue, tensorboard has been kind of a liability because the protobuf dependency turns out to be really fragile. 
Can you share which os you're using and the commands you are running?

**Comment by jorissijs** [comment]
Sure, no problem.
I am running 24.04 with Tensorboard version 2.17.0. When reverting to version 2.12.2 (as recommended in the instructions)  I receive an error that is cannot find BLAS licraries. 

So, I continue by removing everything in the build-folder of RL-tools and then I successfully run the commands, i.e., no tensorboard yet:
"""
cmake .. -DCMAKE_BUILD_TYPE=Release -DRL_TOOLS_ENABLE_TARGETS:BOOL=ON $PLATFORM_BLAS_OPTION
cmake --build . --target rl_environments_pendulum_td3_standalone -j4
"""

Then, I continue with the examples and run the command:
"""
cmake .. -DCMAKE_BUILD_TYPE=Release -DRL_TOOLS_ENABLE_TARGETS:BOOL=ON $PLATFORM_BLAS_OPTION -DRL_TOOLS_ENABLE_TENSORBOARD:BOOL=ON
"""

I receive the following feedback
"""
Build type: Release
C++ Compiler: /usr/bin/c++
Commit hash: b0bb75c2b6748d0eebf6b9877efbc098ff4aaea1
-- The C compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so (found version "3.21.12") 
-- Found Protobuf 3.21.12
-- Found Protobuf Headers /usr/include
-- Found Protobuf Include Dirs /usr/include
-- Generating /home/yoghi/Repositories/rl_tools/external/tensorboard/proto/event.proto
-- Generating /home/yoghi/Repositories/rl_tools/external/tensorboard/proto/projector_config.proto
-- Generating /home/yoghi/Repositories/rl_tools/external/tensorboard/proto/resource_handle.proto
-- Generating /home/yoghi/Repositories/rl_tools/external/tensorboard/proto/summary.proto
-- Generating /home/yoghi/Repositories/rl_tools/external/tensorboard/proto/tensor.proto
-- Generating /home/yoghi/Repositories/rl_tools/external/tensorboard/proto/tensor_shape.proto
-- Generating /home/yoghi/Repositories/rl_tools/external/tensorboard/proto/types.proto
-- Using protobuf_generate
-- Tensorboard library type: STATIC_LIBRARY
-- Configuring done (0.2s)
-- Generating done (0.3s)
-- Build files have been written to: /home/yoghi/Repositories/rl_tools/build
"""

Then, when continuing with the examples
"""
tensorboard --logdir runs
"""

I see that tensorboard is running, yet with the following warnig/error:
"""
E0824 15:14:44.861741 136924970438784 application.py:125] Failed to load plugin WhatIfToolPluginLoader.load; ignoring it.
Traceback (most recent call last):
  File "/home/yoghi/.local/lib/python3.12/site-packages/tensorboard/backend/application.py", line 123, in TensorBoardWSGIApp
    plugin = loader.load(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorboard_plugin_wit/wit_plugin_loader.py", line 57, in load
    from tensorboard_plugin_wit.wit_plugin import WhatIfToolPlugin
  File "/usr/local/lib/python3.12/dist-packages/tensorboard_plugin_wit/wit_plugin.py", line 40, in <module>
    from tensorboard_plugin_wit._utils import common_utils
  File "/usr/local/lib/python3.12/dist-packages/tensorboard_plugin_wit/_utils/common_utils.py", line 17, in <module>
    from tensorboard_plugin_wit._vendor.tensorflow_serving.apis import classification_pb2
  File "/usr/local/lib/python3.12/dist-packages/tensorboard_plugin_wit/_vendor/tensorflow_serving/apis/classification_pb2.py", line 15, in <module>
    from tensorboard_plugin_wit._vendor.tensorflow_serving.apis import input_pb2 as tensorflow__serving_dot_apis_dot_input__pb2
  File "/usr/local/lib/python3.12/dist-packages/tensorboard_plugin_wit/_vendor/tensorflow_serving/apis/input_pb2.py", line 37, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.12/dist-packages/google/protobuf/descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.17.0 at http://localhost:6006/ (Press CTRL+C to quit)
"""

Then, these commands still run successfully:
"""
cmake .. -DCMAKE_BUILD_TYPE=Release -DRL_TOOLS_ENABLE_TARGETS:BOOL=ON $PLATFORM_BLAS_OPTION
./src/rl/environments/pendulum/td3/cpu/rl_environments_pendulum_td3_standalone
"""

However, when I then run;
"""
cmake --build . --target rl_environments_pendulum_td3_blas_tensorboard -j4
"""
I receieve the error that there is no rule related to the target,

**Comment by jonas-eschmann** [comment]
Sorry for the late reply! This is just the gnarly type of issue that protobufs seem to be able to generate ad infinitum. Instead of playing whack-a-mole and fixing these one by one I'm planning to implement a thin logging middleware that connects to a simple logging server that is actually outputting the logs. The logging server would be a simple script in e.g. Python that uses the native Tensorboard or WandB package. 

I'm still weighing the pros and cons of launching this as a subprocess (concern: cross-platform compatibility) or as a separate process (concern: annoying for the user). 
I'm quite busy with other stuff rn but I think I'll be able to implement it by the end of the month.

**Comment by jonas-eschmann** [comment]
Hey @jorissijs 

I now encountered a similar error as you:

```
jonas@jonas:~/rl_tools$ python3 -m tensorboard.main --logdir experiments/
Traceback (most recent call last):
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/home/jonas/.local/lib/python3.8/site-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/main.py", line 53, in <module>
    run_main()
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/main.py", line 39, in run_main
    main_lib.global_init()
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/main_lib.py", line 40, in global_init
    if getattr(tf, "__version__", "stub") == "stub":
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/jonas/.local/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/jonas/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

This is on Ubuntu 20.04 so the default Python version is `3.8`

When I tried it with Python `3.12` it worked:

```
jonas@jonas:~/rl_tools$ python3.12 -m tensorboard.main --logdir experiments/
TensorFlow installation not found - running with reduced feature set.

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

I0910 18:45:27.273801 140573985982208 plugin.py:429] Monitor runs begin
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.17.1 at http://localhost:6006/ (Press CTRL+C to quit)
```

Using a newer Python version might fix your issue as well
